services:
  php:
    build:
      context: ./docker/php
    container_name: symfony-php
    volumes:
      - ./apps:/var/www/html
    networks:
      - symfony
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./apps:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: postgres:15
    container_name: symfony-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./docker/postgre/db-data:/var/lib/postgresql/data
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
